export const RULE_FAMILY_CATALOG = [
  {
    label: 'SEC',
    rulePath: '.agent-context/rules/security.md',
    priority: 10,
    triggers: [
      'auth',
      'authorization',
      'login',
      'password',
      'permission',
      'role',
      'secret',
      'secrets',
      'session',
      'turnstile',
      'jwt',
      'csrf',
      'xss',
      'sql injection',
      'request validation',
      'safe request',
      'access',
      'akses',
      'kebuka',
      'expose',
      'exposed',
      'exposing',
      'credential',
      'credentials',
      'access token',
      'api token',
      'auth token',
      'bearer token',
      'tenant',
      'tenant sebelah',
      'user lain',
    ],
  },
  {
    label: 'API',
    rulePath: '.agent-context/rules/api-docs.md',
    priority: 20,
    triggers: [
      'api',
      'endpoint',
      'route',
      'response',
      'http',
      'webhook',
      'contract',
      'pagination',
      'cli',
      'command',
      'idempotent',
      'idempotency',
      'documented',
      'diagram',
      'mermaid',
    ],
  },
  {
    label: 'ERR',
    rulePath: '.agent-context/rules/error-handling.md',
    priority: 30,
    triggers: [
      'error',
      'errors',
      'exception',
      'fail',
      'failed',
      'failing',
      'bug',
      'crash',
      'stack trace',
      'null',
      'undefined',
      'rollback',
      'debug',
      'gagal',
      'fix',
      'broke',
      'broken',
      'stops',
      'stopped',
      'bermasalah',
      'ga jalan',
      'nggak jalan',
      'tidak jalan',
    ],
  },
  {
    label: 'TEST',
    rulePath: '.agent-context/rules/testing.md',
    priority: 40,
    triggers: [
      'test',
      'tests',
      'testing',
      'spec',
      'assert',
      'assertion',
      'coverage',
      'validate',
      'validation',
      'smoke',
      'unit',
      'integration',
      'benchmark',
      'fixture',
      'fixtures',
      'regression',
      'corpus',
    ],
  },
  {
    label: 'ARCH',
    rulePath: '.agent-context/rules/architecture.md',
    priority: 50,
    triggers: [
      'architecture',
      'boundary',
      'layer',
      'module',
      'structure',
      'refactor',
      'clean up',
      'cleanup',
      'over-engineer',
      'over engineering',
      'abstraction',
      'helper',
      'natural implementation',
      'adaptive context',
      'classifier',
      'resolver',
      'routing',
      'runtime',
      'duplicate',
      'duplicate code',
      'middleware',
      'rapihin',
      'rapikan',
    ],
  },
  {
    label: 'NAME',
    rulePath: '.agent-context/rules/naming-conv.md',
    priority: 60,
    triggers: [
      'naming',
      'name',
      'variable',
      'function name',
      'comment',
      'comments',
      'readable',
      'humanizer',
      'natural code',
      'generic name',
      'namingnya',
      'dibaca',
      'variabel',
    ],
  },
  {
    label: 'FE',
    rulePath: '.agent-context/rules/frontend-architecture.md',
    priority: 70,
    triggers: [
      'ui',
      'ux',
      'frontend',
      'component',
      'screen',
      'layout',
      'responsive',
      'tailwind',
      'redesign',
      'redesain',
      'animation',
      'motion',
      'page',
      'mobile',
      'overlap',
      'overlaps',
      'flicker',
      'flickers',
      'text overlaps',
      'button',
      'layar',
      'layar kecil',
      'kepotong',
      'terpotong',
    ],
  },
  {
    label: 'DATA',
    rulePath: '.agent-context/rules/database-design.md',
    priority: 80,
    triggers: [
      'database',
      'schema',
      'sql',
      'query',
      'table',
      'prisma',
      'model',
      'persistence',
      'index',
      'n+1',
    ],
  },
  {
    label: 'MIG',
    rulePath: '.agent-context/rules/migrations.md',
    priority: 90,
    triggers: [
      'migration',
      'migrate',
      'rollback',
      'backfill',
      'schema change',
      'expand contract',
    ],
  },
  {
    label: 'PERF',
    rulePath: '.agent-context/rules/performance.md',
    priority: 100,
    triggers: [
      'performance',
      'slow',
      'latency',
      'memory',
      'n+1',
      'cache',
      'optimization',
      'throughput',
      'lemot',
      'lambat',
      'bottleneck',
    ],
  },
  {
    label: 'DOCK',
    rulePath: '.agent-context/rules/docker-runtime.md',
    priority: 110,
    triggers: [
      'docker',
      'compose',
      'container',
      'dockerfile',
      'image',
    ],
  },
  {
    label: 'OBS',
    rulePath: '.agent-context/rules/observability.md',
    priority: 120,
    triggers: [
      'log',
      'logging',
      'metric',
      'trace',
      'tracing',
      'alert',
      'observability',
      'monitoring',
      'slo',
      'logs',
      'silent',
      'silently',
    ],
  },
  {
    label: 'RES',
    rulePath: '.agent-context/rules/resilience.md',
    priority: 130,
    triggers: [
      'retry',
      'timeout',
      'fallback',
      'circuit',
      'degraded',
      'resilience',
      'unavailable',
      'recovery',
      'offline',
    ],
  },
  {
    label: 'CFG',
    rulePath: '.agent-context/rules/config-and-flags.md',
    priority: 140,
    triggers: [
      'env',
      'config',
      'configuration',
      'flag',
      'feature flag',
      'setting',
      'settings',
      'secret',
      'key',
      'env var',
    ],
  },
  {
    label: 'JOB',
    rulePath: '.agent-context/rules/background-jobs.md',
    priority: 150,
    triggers: [
      'queue',
      'worker',
      'cron',
      'job',
      'background',
      'scheduler',
    ],
  },
  {
    label: 'EVT',
    rulePath: '.agent-context/rules/event-driven.md',
    priority: 160,
    triggers: [
      'event',
      'events',
      'message',
      'pubsub',
      'kafka',
      'broker',
      'outbox',
      'subscriber',
      'producer',
    ],
  },
  {
    label: 'SVC',
    rulePath: '.agent-context/rules/microservices.md',
    priority: 170,
    triggers: [
      'microservice',
      'microservices',
      'distributed',
      'service split',
      'multi-service',
    ],
  },
  {
    label: 'RT',
    rulePath: '.agent-context/rules/realtime.md',
    priority: 180,
    triggers: [
      'realtime',
      'real-time',
      'websocket',
      'sse',
      'socket',
      'stream',
      'live update',
    ],
  },
  {
    label: 'VER',
    rulePath: '.agent-context/rules/api-versioning.md',
    priority: 190,
    triggers: [
      'version',
      'versioned',
      'versioning',
      'deprecate',
      'deprecation',
      'backward compatible',
      'breaking change',
    ],
  },
  {
    label: 'DEP',
    rulePath: '.agent-context/rules/efficiency-vs-hype.md',
    priority: 200,
    triggers: [
      'dependency',
      'dependencies',
      'package',
      'library',
      'install',
      'npm',
      'framework',
    ],
  },
];

export const PROMPT_CATALOG = [
  {
    promptPath: '.agent-context/prompts/review-code.md',
    triggers: ['review', 'audit', 'check', 'analyze', 'analisa', 'cek'],
  },
  {
    promptPath: '.agent-context/prompts/refactor.md',
    triggers: ['refactor', 'improve', 'fix', 'clean up', 'cleanup', 'rapikan', 'perbaiki'],
  },
  {
    promptPath: '.agent-context/prompts/init-project.md',
    triggers: ['create', 'build', 'new project', 'scaffold', 'fresh project', 'bikin project'],
  },
  {
    promptPath: '.agent-context/prompts/bootstrap-design.md',
    labels: ['FE'],
    triggers: ['ui', 'ux', 'frontend', 'layout', 'screen', 'redesign', 'redesain', 'ulang dari 0', 'research ulang'],
  },
];

export const DOCS_BY_LABEL = {
  ARCH: ['docs/architecture-decision-record.md', 'docs/flow-overview.md'],
  API: ['docs/api-contract.md'],
  DATA: ['docs/database-schema.md'],
  FE: ['docs/DESIGN.md'],
  TEST: ['docs/flow-overview.md'],
};

export const STATE_BY_LABEL = {
  ARCH: ['.agent-context/state/architecture-map.md'],
  DEP: ['.agent-context/state/dependency-map.md'],
};
