export const ADAPTIVE_CONTEXT_FIXTURES = [
  {
    id: 'auth-flow-review',
    requestText: 'Review this login auth flow. Check JWT session handling, API response errors, and what tests should cover.',
    requiredLabels: ['SEC', 'API', 'ERR', 'TEST'],
    allowedLabels: ['SEC', 'API', 'ERR', 'TEST'],
  },
  {
    id: 'real-auth-refactor',
    requestText: 'Tolong refactor auth flow ini, jangan ubah behavior, cek security dan test juga.',
    requiredLabels: ['SEC', 'ARCH', 'TEST'],
    allowedLabels: ['SEC', 'ARCH', 'TEST', 'ERR', 'API'],
  },
  {
    id: 'runtime-hardening',
    requestText: 'Make adaptive context runtime stable. Fix missed implicit cases before moving to ASCX.',
    requiredLabels: ['ARCH', 'TEST', 'ERR'],
    allowedLabels: ['ARCH', 'TEST', 'ERR'],
  },
  {
    id: 'natural-migration-broke',
    requestText: 'Something broke after I pushed the migration yesterday.',
    requiredLabels: ['MIG', 'ERR'],
    allowedLabels: ['MIG', 'ERR'],
  },
  {
    id: 'natural-frontend-mobile-overlap',
    requestText: 'This page flickers on mobile and the text overlaps.',
    requiredLabels: ['FE'],
    allowedLabels: ['FE'],
  },
  {
    id: 'indonesian-access-leak',
    requestText: 'Audit pembayaran ini, takut kebuka akses user lain.',
    requiredLabels: ['SEC'],
    allowedLabels: ['SEC'],
  },
  {
    id: 'indonesian-readable-service',
    requestText: 'Rapihin service ini biar namingnya enak dibaca.',
    requiredLabels: ['ARCH'],
    allowedLabels: ['ARCH'],
  },
  {
    id: 'natural-cron-silent',
    requestText: 'My cron stops silently, need logs and retry.',
    requiredLabels: ['JOB', 'ERR', 'OBS', 'RES'],
    allowedLabels: ['JOB', 'ERR', 'OBS', 'RES'],
  },
  {
    id: 'auth-middleware-duplicate',
    requestText: 'Remove duplicate code in auth middleware.',
    requiredLabels: ['SEC', 'ARCH'],
    allowedLabels: ['SEC', 'ARCH'],
  },
  {
    id: 'indonesian-slow-query',
    requestText: 'Bisa cek kenapa checkout lemot banget pas query order.',
    requiredLabels: ['DATA', 'PERF'],
    allowedLabels: ['DATA', 'PERF'],
  },
  {
    id: 'config-exposing-key',
    requestText: 'Update env var for staging without exposing key.',
    requiredLabels: ['CFG', 'SEC'],
    allowedLabels: ['CFG', 'SEC'],
  },
  {
    id: 'token-budget-context-hardening',
    requestText: 'Tighten adaptive context token budget and benchmark reporting for real request corpus.',
    requiredLabels: ['ARCH', 'TEST'],
    allowedLabels: ['ARCH', 'TEST'],
  },
  {
    id: 'tenant-access-leak-indonesian',
    requestText: 'Pas login, user bisa lihat data tenant sebelah.',
    requiredLabels: ['SEC'],
    allowedLabels: ['SEC'],
  },
  {
    id: 'invoice-worker-no-log',
    requestText: 'Abis deploy, worker invoice ga jalan tapi ga ada error di log.',
    requiredLabels: ['JOB', 'ERR', 'OBS'],
    allowedLabels: ['JOB', 'ERR', 'OBS'],
  },
  {
    id: 'checkout-helper-naming',
    requestText: 'Rapihin nama variabel di checkout helper, jangan bikin abstraction baru.',
    requiredLabels: ['ARCH'],
    allowedLabels: ['ARCH'],
  },
  {
    id: 'mobile-button-cut-off',
    requestText: 'Button checkout kepotong di layar kecil.',
    requiredLabels: ['FE'],
    allowedLabels: ['FE'],
  },
  {
    id: 'production-migration-rollback',
    requestText: 'Migration order sukses locally tapi production rollback.',
    requiredLabels: ['MIG', 'ERR'],
    allowedLabels: ['MIG', 'ERR'],
  },
  {
    id: 'cancel-order-idempotent-endpoint',
    requestText: 'Buat endpoint cancel order idempotent dan documented.',
    requiredLabels: ['API'],
    allowedLabels: ['API'],
  },
  {
    id: 'production-env-secret-error',
    requestText: 'Env production salah kebaca, jangan tampilin secret di error.',
    requiredLabels: ['CFG', 'SEC', 'ERR'],
    allowedLabels: ['CFG', 'SEC', 'ERR'],
  },
  {
    id: 'websocket-reconnect-timeout',
    requestText: 'WebSocket reconnect sering timeout, perlu fallback.',
    requiredLabels: ['RT', 'RES'],
    allowedLabels: ['RT', 'RES'],
  },
  {
    id: 'invoice-query-timeout-nplusone',
    requestText: 'Query invoice timeout dan N+1.',
    requiredLabels: ['DATA', 'PERF', 'RES'],
    allowedLabels: ['DATA', 'PERF', 'RES'],
  },

  {
    id: 'frontend-redesign',
    requestText: 'Redesign this frontend screen from zero with responsive layout, motion, and UI design docs.',
    requiredLabels: ['FE'],
    allowedLabels: ['FE'],
  },
  {
    id: 'database-migration-failure',
    requestText: 'The database migration fails during rollback after a schema change. Check query impact and validation coverage.',
    requiredLabels: ['DATA', 'MIG', 'ERR', 'TEST'],
    allowedLabels: ['DATA', 'MIG', 'ERR', 'TEST'],
  },
  {
    id: 'docker-env-setup',
    requestText: 'Set up Docker Compose with env config and validation so the container can run locally.',
    requiredLabels: ['DOCK', 'CFG', 'TEST'],
    allowedLabels: ['DOCK', 'CFG', 'TEST'],
  },
  {
    id: 'worker-retry-observability',
    requestText: 'Fix the queue worker retry flow. It publishes events, needs fallback behavior, and should log trace data.',
    requiredLabels: ['JOB', 'EVT', 'RES', 'OBS', 'ERR'],
    allowedLabels: ['JOB', 'EVT', 'RES', 'OBS', 'ERR'],
  },
  {
    id: 'service-refactor-clean-code',
    requestText: 'Refactor this service module. Clean up helper names, avoid over-engineering, and keep tests readable.',
    requiredLabels: ['ARCH', 'TEST'],
    allowedLabels: ['ARCH', 'TEST'],
  },
  {
    id: 'versioned-api-endpoint',
    requestText: 'Design a versioned API endpoint contract with safe request validation, error responses, and backward compatibility.',
    requiredLabels: ['API', 'VER', 'ERR', 'SEC', 'TEST'],
    allowedLabels: ['API', 'VER', 'ERR', 'SEC', 'TEST'],
  },
  {
    id: 'slow-query-performance',
    requestText: 'The SQL query is slow and may be an N+1 issue. Add observability and a performance test.',
    requiredLabels: ['PERF', 'DATA', 'OBS', 'TEST'],
    allowedLabels: ['PERF', 'DATA', 'OBS', 'TEST'],
  },
  {
    id: 'config-secret-feature-flag',
    requestText: 'Add a feature flag from env config without leaking secrets in errors.',
    requiredLabels: ['CFG', 'SEC', 'ERR'],
    allowedLabels: ['CFG', 'SEC', 'ERR'],
  },
  {
    id: 'realtime-stream-contract',
    requestText: 'Plan a realtime WebSocket stream API with timeout recovery and monitoring.',
    requiredLabels: ['RT', 'API', 'RES', 'OBS'],
    allowedLabels: ['RT', 'API', 'RES', 'OBS'],
  },
];
