import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');

async function fileExists(filePath) {
  try {
    await fs.stat(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readTextFile(filePath) {
  return fs.readFile(filePath, 'utf8');
}

async function writeTextFile(filePath, content) {
  return fs.writeFile(filePath, content, 'utf8');
}

async function bumpVersion() {
  const newVersion = process.argv[2];
  if (!newVersion || !/^\d+\.\d+\.\d+$/.test(newVersion)) {
    console.error('Usage: node scripts/bump-version.mjs <new-version>');
    console.error('Example: node scripts/bump-version.mjs 2.1.0');
    process.exit(1);
  }

  console.log(`Starting version bump to ${newVersion}...`);

  // 1. Update package.json
  const packageJsonPath = path.join(ROOT_DIR, 'package.json');
  const packageJsonContent = await readTextFile(packageJsonPath);
  const packageJson = JSON.parse(packageJsonContent);
  const oldVersion = packageJson.version;
  
  if (oldVersion === newVersion) {
    console.log(`Version is already ${newVersion}. Exiting.`);
    process.exit(0);
  }

  packageJson.version = newVersion;
  await writeTextFile(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
  console.log(`Updated package.json (was ${oldVersion})`);

  // 2. Update package-lock.json when it exists.
  const packageLockPath = path.join(ROOT_DIR, 'package-lock.json');
  if (await fileExists(packageLockPath)) {
    const packageLock = JSON.parse(await readTextFile(packageLockPath));
    if (packageLock.name === packageJson.name) {
      packageLock.version = newVersion;
    }
    if (packageLock.packages?.['']?.name === packageJson.name) {
      packageLock.packages[''].version = newVersion;
    }
    await writeTextFile(packageLockPath, JSON.stringify(packageLock, null, 2) + '\n');
    console.log('Updated package-lock.json');
  }

  // 3. Update docs/deep-analysis-and-roadmap-backlog.md
  const roadmapPath = path.join(ROOT_DIR, 'docs', 'deep-analysis-and-roadmap-backlog.md');
  if (await fileExists(roadmapPath)) {
    let roadmapContent = await readTextFile(roadmapPath);
    roadmapContent = roadmapContent.replace(`Current Version: ${oldVersion}`, `Current Version: ${newVersion}`);
    await writeTextFile(roadmapPath, roadmapContent);
    console.log('Updated docs/deep-analysis-and-roadmap-backlog.md');
  }

  // 4. Update legacy root adapters that carry release metadata.
  const legacyAdapterFiles = ['.cursorrules', '.windsurfrules'];
  for (const legacyAdapterFile of legacyAdapterFiles) {
    const legacyAdapterPath = path.join(ROOT_DIR, legacyAdapterFile);
    if (await fileExists(legacyAdapterPath)) {
      const legacyAdapterContent = await readTextFile(legacyAdapterPath);
      const updatedLegacyAdapterContent = legacyAdapterContent.replace(
        /Generated by Agentic-Senior-Core CLI v\d+\.\d+\.\d+/,
        `Generated by Agentic-Senior-Core CLI v${newVersion}`
      );
      await writeTextFile(legacyAdapterPath, updatedLegacyAdapterContent);
      console.log(`Updated ${legacyAdapterFile}`);
    }
  }

  // 5. Update CHANGELOG.md
  const changelogPath = path.join(ROOT_DIR, 'CHANGELOG.md');
  if (await fileExists(changelogPath)) {
    let changelogContent = await readTextFile(changelogPath);
    
    // Check if new version already has an entry
    if (!changelogContent.includes(`## ${newVersion}`)) {
      const today = new Date().toISOString().split('T')[0];
      const newEntry = `## ${newVersion} - ${today}\n### Added\n- \n\n### Changed\n- \n\n### Fixed\n- \n\n`;
      
      // Find the first version heading "## x.x.x"
      const firstHeadingIndex = changelogContent.search(/^## \d+\.\d+\.\d+/m);
      if (firstHeadingIndex !== -1) {
        changelogContent = changelogContent.slice(0, firstHeadingIndex) + newEntry + changelogContent.slice(firstHeadingIndex);
        await writeTextFile(changelogPath, changelogContent);
        console.log('Prepended new entry to CHANGELOG.md');
      }
    } else {
      console.log(`CHANGELOG.md already has an entry for ${newVersion}`);
    }
  }

  console.log(`\nVersion successfully bumped from ${oldVersion} to ${newVersion}!`);
  console.log('Remember to fill out your CHANGELOG.md before pushing.');
}

bumpVersion().catch(e => {
  console.error('Fatal error:', e);
  process.exit(1);
});
